apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-juyy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-juyy
    app.kubernetes.io/part-of: tkrw-pr714-0075-0006-app
  name: devfile-sample-juyy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-juyy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-juyy
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0006-tenant/tkrw-pr714-0075-0006-app/devfile-sample-juyy@sha256:58b608065cb5fe0157d26a97d0300f739bfc7b10287c2d7599a6e04581a0b46b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
